
include toolchain.mk

FORCE:

md5: FORCE
	cd md5; \
	$(ndkbuild); \
	cd -

md5_clean: FORCE
	cd md5; \
	$(ndkbuild) clean; \
	cd -

sha1: FORCE
	cd sha1; \
	$(ndkbuild); \
	cd -

sha1_clean: FORCE
	cd sha1; \
	$(ndkbuild) clean; \
	cd -

base64: FORCE
	cd base64 ; \
	$(ndkbuild) ; \
	cd -

base64_clean: FORCE
	cd base64; \
	$(ndkbuild) clean; \
	cd -

crc32: FORCE
	cd crc32 ; \
	$(ndkbuild) ; \
	cd -

crc32_clean: FORCE
	cd crc32; \
	$(ndkbuild) clean; \
	cd -